// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/GetArea/GetArea.proto

package go_micro_srv_GetArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	//返回错误码
	Errno string `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	//返回错误信息
	Errmsg string `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	//用自定义类型返回的数组
	Data                 []*Response_Address `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() []*Response_Address {
	if m != nil {
		return m.Data
	}
	return nil
}

//返回数据类型
type Response_Address struct {
	Aid                  int32    `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	Aname                string   `protobuf:"bytes,2,opt,name=aname,proto3" json:"aname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Address) Reset()         { *m = Response_Address{} }
func (m *Response_Address) String() string { return proto.CompactTextString(m) }
func (*Response_Address) ProtoMessage()    {}
func (*Response_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{2, 0}
}

func (m *Response_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Address.Unmarshal(m, b)
}
func (m *Response_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Address.Marshal(b, m, deterministic)
}
func (m *Response_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Address.Merge(m, src)
}
func (m *Response_Address) XXX_Size() int {
	return xxx_messageInfo_Response_Address.Size(m)
}
func (m *Response_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Address proto.InternalMessageInfo

func (m *Response_Address) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *Response_Address) GetAname() string {
	if m != nil {
		return m.Aname
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{3}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{4}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{5}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c643115bb4a9c45, []int{6}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetArea.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetArea.Response")
	proto.RegisterType((*Response_Address)(nil), "go.micro.srv.GetArea.Response.Address")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.GetArea.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.GetArea.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.GetArea.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.GetArea.Pong")
}

func init() { proto.RegisterFile("proto/GetArea/GetArea.proto", fileDescriptor_2c643115bb4a9c45) }

var fileDescriptor_2c643115bb4a9c45 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xf2, 0x25, 0x69, 0x74, 0xbc, 0xd4, 0x25, 0x48, 0x68, 0x69, 0x29, 0x7b, 0x90, 0x78,
	0x59, 0xb1, 0xde, 0xbc, 0x15, 0x2c, 0x82, 0x20, 0xc8, 0x8a, 0x3f, 0x60, 0x6d, 0x86, 0x10, 0x24,
	0xbb, 0x75, 0x67, 0x2b, 0xf8, 0x8b, 0xfc, 0x9b, 0x92, 0xcd, 0x86, 0x7a, 0x68, 0x3d, 0xe5, 0xbd,
	0x79, 0x33, 0x99, 0xf7, 0x66, 0x61, 0xba, 0xb5, 0xc6, 0x99, 0xeb, 0x07, 0x74, 0x2b, 0x8b, 0x6a,
	0xf8, 0x0a, 0x5f, 0x65, 0x79, 0x6d, 0x44, 0xdb, 0x6c, 0xac, 0x11, 0x64, 0x3f, 0x45, 0xd0, 0xf8,
	0x14, 0xb2, 0x27, 0x24, 0x52, 0x35, 0xb2, 0x31, 0xc4, 0xa4, 0xbe, 0x8a, 0x68, 0x11, 0x95, 0xa7,
	0xb2, 0x83, 0x7c, 0x06, 0x99, 0xc4, 0x8f, 0x1d, 0x92, 0x63, 0x0c, 0x12, 0xad, 0x5a, 0x0c, 0xaa,
	0xc7, 0xfc, 0x3b, 0x82, 0x13, 0x89, 0xb4, 0x35, 0x9a, 0x90, 0xe5, 0x90, 0xae, 0xad, 0xd5, 0x26,
	0x74, 0xf4, 0x84, 0x5d, 0xc0, 0x68, 0x6d, 0x6d, 0x4b, 0x75, 0xf1, 0xdf, 0x97, 0x03, 0x63, 0x77,
	0x90, 0xdc, 0x2b, 0xa7, 0x8a, 0x78, 0x11, 0x97, 0x67, 0xcb, 0x4b, 0x71, 0xc8, 0x9b, 0x18, 0xfe,
	0x2d, 0x56, 0x55, 0x65, 0x91, 0x48, 0xfa, 0x99, 0xc9, 0x0d, 0x64, 0xa1, 0xd0, 0x59, 0x56, 0x4d,
	0xe5, 0x57, 0xa6, 0xb2, 0x83, 0x9d, 0x0d, 0xe5, 0x8d, 0xf6, 0xfb, 0x7a, 0xc2, 0x4b, 0x18, 0xbf,
	0x38, 0x8b, 0xaa, 0x6d, 0x74, 0x3d, 0x24, 0xca, 0x21, 0xdd, 0x98, 0x9d, 0x76, 0x7e, 0x3a, 0x96,
	0x3d, 0xe1, 0x57, 0x70, 0xfe, 0xab, 0x73, 0x9f, 0xed, 0x40, 0xeb, 0x1c, 0x92, 0xe7, 0x46, 0xd7,
	0x5d, 0x46, 0x72, 0xd6, 0xbc, 0x63, 0x90, 0x03, 0xf3, 0xba, 0x39, 0xae, 0x2f, 0x5f, 0x21, 0x0b,
	0x49, 0xd9, 0xe3, 0x1e, 0xce, 0x8e, 0xdd, 0xc2, 0xbb, 0x9e, 0xcc, 0xff, 0x3e, 0x15, 0xff, 0xf7,
	0x36, 0xf2, 0xcf, 0x7d, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xeb, 0x78, 0xfa, 0x0d, 0x02,
	0x00, 0x00,
}
